### ISSUE TITLE
folderAnnotation insufficient privileges

### ISSUE THREAD

**Issue by nrobert13** [kiwigrid/k8s-sidecar#101]
Hi guys,

I'm using grafana helm chart which comes with your image as a sidecar and having some difficulties with the folderAnnotation:

```
Error: insufficient privileges to create SRE. Skipping prometheus-overview.json.
```
here's the annotation on the configmap:
```
  annotations:                                                                                                                                                                                                                                                                      
    grafana-dashboard-folder: SRE
```
and the env var:

```
env:
- name: METHOD
- name: FOLDER_ANNOTATION                                                                                                                                                                                                                                                      
  value: grafana-dashboard-folder
- name: LABEL                                                                                                                                                                
  value: grafana_dashboard
- name: FOLDER
  value: /tmp/dashboards
- name: RESOURCE
  value: both                                                                                                                                                                                                                        image: kiwigrid/k8s-sidecar:1.1.0
```

also tried to exec into the container and create the folder manually, and it works. Not sure why the app is complaining about permissions.

```
/app $ id
uid=472 gid=472 groups=472
/app $ mkdir /tmp/dashboards/SRE ; echo $?
0
/app $
```
