### ISSUE TITLE
Dashboards in their own Grafana folder

### ISSUE THREAD

**Issue by aceeric** [kiwigrid/k8s-sidecar#141]
This is a question/feature request: I can see how to locate the dashboards from a `ConfigMap` into their own subdirectory in the Grafana pod using the FOLDER_ANNOTATION env var in the sidecar, and then annotating the `ConfigMap`.  We're using RKE2, which uses your sidecar to collect up dashboards (cluster-wide, in our case.) Since there could be many such dashboards it would be nice to use the Grafana _folder_ feature to organize dashboards by folders. Otherwise everything maps into the _Default_ Grafana folder which can thus become lengthy.

Have you considered providing a way to project dashboards into Grafana such that they are contributed by their own provider. In other words - define a provider (say, a ConfigMap) like so:
```
...
kind: ConfigMap
data:
  providers:
  - name: my-provider
    orgId: (one-up, somehow...)
    folder: 'My Custom Dashboard Folder'
    options:
      path: /tmp/my-custom-dashboards
```
And then have this provider merged into `/etc/grafana/provisioning/dashboards/sc-dashboard-providers.yaml`
