### ISSUE TITLE
Cannot download binary files

### ISSUE THREAD

**Issue by svolland-csgroup** [kiwigrid/k8s-sidecar#250]
There are some issues that prevent downloading binary files, i.e. using `binaryData` config maps with `*.url` keys.
- download url is not correctly decoded (base64 binary data is not decoded to a string)
- data is downloaded as text, which fails when writing the file in binary mode

The issue can be reproduced with the following config map to download kubectl (just as an example)

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: download-kubectl
  labels:
     download_binary: "1"
binaryData:
  # Download https://storage.googleapis.com/kubernetes-release/release/v1.26.0/bin/linux/amd64/kubectl
  kubectl.url: "aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL2t1YmVybmV0ZXMtcmVsZWFzZS9yZWxlYXNlL3YxLjI2LjAvYmluL2xpbnV4L2FtZDY0L2t1YmVjdGw="
```
