### ISSUE TITLE
folder annotation invalid character set

### ISSUE THREAD

**Issue by r1m** [kiwigrid/k8s-sidecar#45]
I ran into an issue trying to use the folder annotation. It raises an error saying that label value contains invalid characters.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap
  labels:
    k8s-sidecar-target-directory: /var/lib/grafana/dashboards/test
data:
  hello.world:  Hello World!
```

```sh
The ConfigMap "sample-configmap" is invalid: metadata.labels: Invalid value: "/var/lib/grafana/dashboards/test": a valid label must be an empty string or consist of alphanumeric characters,
'-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```
After digging a bit, I found that this is true if we refer to the k8s doc:
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
And it's what the k8s validation tool expects : 
https://github.com/kubernetes/apimachinery/blob/4147c925140e4e3aa51d6b46b41650821712d457/pkg/util/validation/validation.go#L88

Is it possible to find a new way of setting folder, that makes k8s validation happy ?
