### ISSUE TITLE
Watching stops working after 10 minutes

### ISSUE THREAD

**Issue by PeterGerrard** [kiwigrid/k8s-sidecar#85]
Watching a set of configmaps fails to be alerted of new changes after 10 minutes of no changes.

##Repro steps
1. Install the following configmap into a cluster
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-test-dashboard
  labels:
    grafana_dashboard: "1"
data:
  cm-test.json: {}
```

1. Install the sidecar into the cluster
```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - env:
        - name: METHOD
        - name: LABEL
          value: grafana_dashboard
        - name: FOLDER
          value: /tmp/dashboards
        - name: RESOURCE
          value: both
      image: kiwigrid/k8s-sidecar:0.1.178
      imagePullPolicy: IfNotPresent
      name: grafana-sc-dashboard
```

1. Wait 10 minutes
1. Make a change to the config map and update in the cluster

## Expected Behaviour
Will see a modification occur

## Actual Behaviour
Nothing

---

Done on AKS with kubernetes version 1.16.10
